export enum AUTH_ITEM_TYPE {
  TYPE_ROLE = 1,
  TYPE_RESOURCE = 2,
  TYPE_ACTION = 3,
}

export enum ROLES {
  ROLE_USER = 'ROLE_USER',
  ROLE_ADMIN = 'ROLE_ADMIN',
  ROLE_SYSTEM = 'ROLE_SYSTEM',
}

export enum RESOURCES {
  RESOURCE_MAIN_MENU = 'RESOURCE_MAIN_MENU',
}

export enum ACTIONS {
  // Menu Dashboard
  ACTION_MAIN_MENU_DASHBOARD = 'ACTION_MAIN_MENU_DASHBOARD',

  // Menu Catalogs
  ACTION_MAIN_MENU_CATALOG = 'ACTION_MAIN_MENU_CATALOG',
  ACTION_MAIN_MENU_CATALOG_LANGUAGE = 'ACTION_MAIN_MENU_CATALOG_LANGUAGE',
  ACTION_MAIN_MENU_CATALOG_VENDOR = 'ACTION_MAIN_MENU_CATALOG_VENDOR',
  ACTION_MAIN_MENU_CATALOG_LOCATION = 'ACTION_MAIN_MENU_CATALOG_LOCATION',
  ACTION_MAIN_MENU_CATALOG_PRODUCT_CATEGORY = 'ACTION_MAIN_MENU_CATALOG_PRODUCT_CATEGORY',
  ACTION_MAIN_MENU_CATALOG_UNIT_OF_MEASURE = 'ACTION_MAIN_MENU_CATALOG_UNIT_OF_MEASURE',
  ACTION_MAIN_MENU_CATALOG_SYSTEM = 'ACTION_MAIN_MENU_CATALOG_SYSTEM',
  ACTION_MAIN_MENU_CATALOG_SYSTEM_MODEL = 'ACTION_MAIN_MENU_CATALOG_SYSTEM_MODEL',
  ACTION_MAIN_MENU_DELIVERY_ZONE = 'ACTION_MAIN_MENU_DELIVERY_ZONE',
  ACTION_MAIN_MENU_TAX_AREA_CODE = 'ACTION_MAIN_MENU_TAX_AREA_CODE',
  ACTION_MAIN_MENU_CUSTOMER = 'ACTION_MAIN_MENU_CUSTOMER',
  ACTION_MAIN_MENU_CUSTOMER_CONTACT = 'ACTION_MAIN_MENU_CUSTOMER_CONTACT',

  //Menu Inventory
  ACTION_MAIN_MENU_INVENTORY = 'ACTION_MAIN_MENU_INVENTORY',
  ACTION_MAIN_MENU_INVENTORY_PRODUCT = 'ACTION_MAIN_MENU_INVENTORY_PRODUCT',
  ACTION_MAIN_MENU_INVENTORY_MOVEMENT_TYPE = 'ACTION_MAIN_MENU_INVENTORY_MOVEMENT_TYPE',
  ACTION_MAIN_MENU_INVENTORY_STOCK_POSITION = 'ACTION_MAIN_MENU_INVENTORY_STOCK_POSITION',
  ACTION_MAIN_MENU_INVENTORY_MOVEMENT = 'ACTION_MAIN_MENU_INVENTORY_MOVEMENT',
  ACTION_MAIN_MENU_INVENTORY_ITEMS = 'ACTION_MAIN_MENU_INVENTORY_ITEMS',
  // Menu Admin
  ACTION_MAIN_MENU_ADMIN = 'ACTION_MAIN_MENU_ADMIN',
  ACTION_MAIN_MENU_ADMIN_USERS = 'ACTION_MAIN_MENU_ADMIN_USERS',
}
